import turtle

turtle.setup(width=800, height=600)
turtle.title("Dibujo de un elefante")

turtle.bgcolor("white")

turtle.penup()
turtle.goto(-100, 0)
turtle.pendown()

turtle.color("gray")
turtle.begin_fill()
turtle.circle(50, 180)
turtle.circle(70, 180)
turtle.end_fill()

turtle.penup()
turtle.goto(0, 70)
turtle.pendown()
turtle.begin_fill()
turtle.circle(30)
turtle.end_fill()

turtle.penup()
turtle.goto(30, 70)
turtle.pendown()
turtle.color("gray")
turtle.pensize(10)
turtle.right(45)
turtle.forward(40)
turtle.right(90)
turtle.forward(60)
turtle.right(90)
turtle.forward(40)

turtle.penup()
turtle.goto(10, 90)
turtle.pendown()
turtle.color("black")
turtle.begin_fill()
turtle.circle(5)
turtle.end_fill()

turtle.penup()
turtle.goto(-40, 70)
turtle.pendown()
turtle.color("gray")
turtle.begin_fill()
turtle.right(45)
turtle.forward(20)
turtle.right(90)
turtle.forward(40)
turtle.right(90)
turtle.forward(20)
turtle.end_fill()

turtle.penup()
turtle.goto(-50, -30)
turtle.pendown()
turtle.color("gray")
turtle.begin_fill()
turtle.right(45)
turtle.forward(50)
turtle.right(90)
turtle.forward(20)
turtle.right(90)
turtle.forward(50)
turtle.end_fill()

turtle.penup()
turtle.goto(20, -30)
turtle.pendown()
turtle.color("gray")
turtle.begin_fill()
turtle.right(45)
turtle.forward(50)
turtle.right(90)
turtle.forward(20)
turtle.right(90)
turtle.forward(50)
turtle.end_fill()

turtle.mainloop()